### ISSUE TITLE
Support the new location for chromedriver binary version information

### ISSUE THREAD

**Issue by jromelague** [bugph0bia/chromedriver-binary-sync#1]
Hi,

The internally used chromedriver-binary-auto package should be updated so that the new location for checking the chrome driver binary version is updated (see commit https://github.com/danielkaiser/python-chromedriver-binary/commit/a7df8baabea16aaa4e67e3535f0d2d219e66696b).

Best regards,
Jérôme.

**Comment by bugph0bia** [comment]
Hi @jromelague,

Thank you for providing this information.
I will create a new version that supports this.

**Comment by bugph0bia** [comment]
Hi @jromelague,

Bugfix version of v0.2.0 has been released.
Please check it.

**Comment by jromelague** [comment]
Hi @bugph0bia ,

I've also update the chromedriver-binary-auto package and it works.
Many thanks for your fix.
