### ISSUE TITLE
Error when the chrome driver is already installed

### ISSUE THREAD

**Issue by jromelague** [bugph0bia/chromedriver-binary-sync#2]
Hi,

I face an error when I try to update the chrome driver:
`C:\Windows\System32>cmd /c python.exe -c "import chromedriver_binary_sync; chromedriver_binary_sync.download(\"C:\Program Files\Google\Chrome\Application\")"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\chromedriver_binary_sync\__init__.py", line 95, in download
    os.rename(os.path.join(chromedriver_dir, filename), os.path.join(chromedriver_dir, path_elements[-1]))
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Program Files\\Google\\Chrome\\Application\\chromedriver-win64/chromedriver.exe' -> 'C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe'`

os.rename fails to overwrite the existing files. I think that [os.replace](https://docs.python.org/3/library/os.html#os.replace) should be used instead.
But I don't understand why it was working before.

Best regards.

**Comment by bugph0bia** [comment]
Hi @jromelague

Thank you for contacting me.
I was able to confirm the error as well.

During my research, I found the following:

1. An older version of `chromedriver.exe` exists and attempts to overwrite a newer version of `chromedriver.exe` fail.
2. It only happens in directories that require administrator rights to write (e.g. under `C:\Program Files`).
3. Changing `os.rename` to `os.replace` as you suggested succeeds.
    - The use of `os.rename` follows the original version of `chromedriver-binary-auto`.
    - I assume the difference is in the way the Win32 API (e.g. MoveFileEx) is called in each function.
        - Reference: https://stackoverflow.com/questions/69363867/difference-between-os-replace-and-os-rename

I don't know why the error started to appear either, but the reason may be related to 2 above.
Is it possible that you were calling the function under `C:\Program Files` when you previously confirmed success?
Sorry, I did not confirm that it worked under `C:\Program Files`, so I do not have that information.

I will prepare a version with `os.rename` changed to `os.replace`.
Please wait a little longer.

**Comment by bugph0bia** [comment]
Hi @jromelague,

Bugfix version of v0.2.2 has been released.
Please check it.

**Comment by bugph0bia** [comment]
Memo:

`os.replace` passes the flag `MOVEFILE_REPLACE_EXISTING` as the third argument `dwFlag` when calling `MoveFileEx`, while `os.rename` does not pass any flag. That is the only difference.

https://github.com/python/cpython/blob/78e6d72e38ef4b490f0098b644454031f20ae361/Modules/posixmodule.c#L5528

**Comment by jromelague** [comment]
Hi @bugph0bia 

I confirm that the new version fixes the issue.

Many thanks !
